<?php
$labels = array(
    'name'                => _x( 'MI Carousels', 'Post Type General Name', 'mi-carousel-slider' ),
    'singular_name'       => _x( 'MI Carousel', 'Post Type Singular Name', 'mi-carousel-slider' ),
    'menu_name'           => __( 'MI Carousel', 'mi-carousel-slider' ),
    'parent_item_colon'   => __( 'Parent MI Carousel:', 'mi-carousel-slider' ),
    'all_items'           => __( 'All MI Carousels', 'mi-carousel-slider' ),
    'view_item'           => __( 'View MI Carousel', 'mi-carousel-slider' ),
    'add_new_item'        => __( 'Add New MI Carousel', 'mi-carousel-slider' ),
    'add_new'             => __( 'New MI Carousel', 'mi-carousel-slider' ),
    'edit_item'           => __( 'Edit MI Carousel', 'mi-carousel-slider' ),
    'update_item'         => __( 'Update MI Carousel', 'mi-carousel-slider' ),
    'search_items'        => __( 'Search MI Carousels', 'mi-carousel-slider' ),
    'not_found'           => __( 'No MI Carousels found', 'mi-carousel-slider' ),
    'not_found_in_trash'  => __( 'No MI Carousel found in Trash', 'mi-carousel-slider' ),
    'featured_image'        => __( 'Banner Image', 'mi-carousel-slider' ),
    'set_featured_image'    => __( 'Set Banner image', 'mi-carousel-slider' ),
    'remove_featured_image' => __( 'Remove Banner image', 'mi-carousel-slider' ),
    'use_featured_image'    => __( 'Use as Banner image', 'mi-carousel-slider' ),
    'insert_into_item'      => __( 'Insert into Banner', 'mi-carousel-slider' ),
    'uploaded_to_this_item' => __( 'Uploaded to this Banner', 'mi-carousel-slider' ),
    'items_list'            => __( 'MI Carousel list', 'mi-carousel-slider' ),
    'items_list_navigation' => __( 'MI Carousel list navigation', 'mi-carousel-slider' ),
    'filter_items_list'     => __( 'Filter MI Carousel list', 'mi-carousel-slider' ),
);
$args = array(
    'label'               => __( 'MI Carousel', 'mi-carousel-slider' ),
    'description'         => __( 'MI Carousel information pages', 'mi-carousel-slider' ),
    'labels'              => $labels,
    'supports'              => array( 'title', 'page-attributes','thumbnail'),
    'public'              => false,
    'show_ui'             => true,
    'show_in_menu'        => true,
    'show_in_nav_menus'   => true,
    'show_in_admin_bar'   => true,
    'menu_position'       => 8,
    'menu_icon'           => plugin_dir_url(__FILE__).'../images/mi-carousel-slide-icon.png',
    'can_export'          => true,
    'has_archive'         => false,
    'exclude_from_search' => false,
    'publicly_queryable'  => false,
    'capability_type'     => 'post',
    'show_in_rest'        => false,
);
register_post_type( 'mi_carousel_slider', $args );
